export const TRANSACTION_CREATE_REQUEST = "TRANSACTION_CREATE_REQUEST";
export const TRANSACTION_CREATE_SUCCESS = "TRANSACTION_CREATE_SUCCESS";
export const TRANSACTION_CREATE_FAIL = "TRANSACTION_CREATE_FAIL";

export const TRANSACTION_DELETE_REQUEST = "TRANSACTION_DELETE_REQUEST";
export const TRANSACTION_DELETE_SUCCESS = "TRANSACTION_DELETE_SUCCESS";
export const TRANSACTION_DELETE_FAIL = "TRANSACTION_DELETE_FAIL";
