export const ADD_TO_TRANSACTION_LIST = "ADD_TO_TRANSACTION_LIST";
export const DELETE_FROM_TRANSACTION_LIST = "DELETE_FROM_TRANSACTION_LIST";

export const TRANSACTION_LIST_REQUEST = "TRANSACTION_LIST_REQUEST";
export const TRANSACTION_LIST_SUCCESS = "TRANSACTION_LIST_SUCCESS";
export const TRANSACTION_LIST_FAIL = "TRANSACTION_LIST_FAIL";

export const TRANSACTION_LIST_RESET = "TRANSACTION_LIST_RESET";
